using System;
using MediaBrowser.Model.Plugins;

namespace Jellyfin.Plugin.ArrDashboard.Configuration;

/// <summary>
/// A single Sonarr or Radarr server.
/// </summary>
public class ArrInstance
{
    /// <summary>
    /// Stable identifier used by the API and the web UI. Generated by the config page.
    /// </summary>
    public string Id { get; set; } = string.Empty;

    /// <summary>
    /// Friendly name, e.g. "Sonarr" or "Sonarr 4K".
    /// </summary>
    public string Name { get; set; } = string.Empty;

    /// <summary>
    /// Base URL including any reverse proxy path, e.g. http://192.168.1.10:8989 or https://host/sonarr.
    /// </summary>
    public string Url { get; set; } = string.Empty;

    /// <summary>
    /// API key from Settings -> General.
    /// </summary>
    public string ApiKey { get; set; } = string.Empty;

    public bool Enabled { get; set; } = true;
}

public class PluginConfiguration : BasePluginConfiguration
{
    public ArrInstance[] SonarrInstances { get; set; } = Array.Empty<ArrInstance>();

    public ArrInstance[] RadarrInstances { get; set; } = Array.Empty<ArrInstance>();

    /// <summary>
    /// How long aggregated responses are cached, in seconds. 0 disables caching.
    /// </summary>
    public int CacheSeconds { get; set; } = 30;

    /// <summary>
    /// Per-request timeout when talking to Sonarr/Radarr, in seconds.
    /// </summary>
    public int RequestTimeoutSeconds { get; set; } = 20;

    /// <summary>
    /// Default number of days of history shown before today on the calendar.
    /// </summary>
    public int CalendarDaysPast { get; set; } = 7;

    /// <summary>
    /// Default number of days shown after today on the calendar.
    /// </summary>
    public int CalendarDaysFuture { get; set; } = 28;

    /// <summary>
    /// When false, only Jellyfin administrators can read the dashboard endpoints.
    /// </summary>
    public bool AllowNonAdminAccess { get; set; } = true;

    /// <summary>
    /// When false, unmonitored items are hidden from the calendar.
    /// </summary>
    public bool IncludeUnmonitored { get; set; }

    /// <summary>
    /// Maximum rows fetched per instance for list endpoints.
    /// </summary>
    public int MaxRecordsPerInstance { get; set; } = 200;
}
